feat: add history personalized widget render and track events
chaordic/onsite-demo pull request #12
Opened 2018-12-06 21:45 UTC by cloped

Adicionando suporte à vitrine Push.

Readme no master explica como testar.

Mudar inputs para lojar com a push ( uma delas é a oppa )

2018-12-07 21:37 UTC, CrashToDesktop commented
Fui testar na Marisa e não carregou, no console aparece esse erro:

![screenshot from 2018-11-23 15-21-01](https://user-images.githubusercontent.com/7432187/49673995-c97f0680-fa46-11e8-9a45-2ca25b2ec18d.png)

Nome: home
Source: desktop

2018-12-10 15:23 UTC, limafm commented
Pra mim deu esse mesmo erro do @CrashToDesktop

2018-12-12 18:45 UTC, marxguimaraes-bdev requested changes
Só umas correções pequenas

2018-12-12 18:45 UTC, CrashToDesktop commented on src/components/historyWidget.js
> +      // If there is no references carousel render as a default widget.
Sugestão: `There is no reference carousel` no singular ou `There are no reference carousels` no plural.

2018-12-12 18:45 UTC, CrashToDesktop commented on src/components/pushWidget.js
> +   * Widget id keeps the same and the selected menu label changes.
`Widget id stays the same`

2018-12-12 21:51 UTC, icastro085 requested changes

2018-12-12 21:51 UTC, icastro085 commented on src/components/historyWidget.js
> +  const tuple = `${widget.id} ${refs[0].id}`;
trocar o espaço para "-" ou remover o espaço

2018-12-12 21:51 UTC, icastro085 commented on src/components/pushWidget.js
> +  const tuple = `${widget.id} ${selectedMenu.label}`;
aqui, pode remover o espaço ou trocar por "-"

2018-12-12 21:51 UTC, icastro085 commented on src/components/pushWidget.js
> +      if (menus[index].selected === true) {
pode ser:
```javascript
if (menus[index].selected) {
```

2018-12-12 21:51 UTC, icastro085 commented on src/components/pushWidget.js
> +    if (menus !== undefined) {
poderia ser:
```javascript
if (menus) {
```

2018-12-17 20:25 UTC, icastro085 requested changes

2018-12-17 20:25 UTC, icastro085 commented on src/components/pushWidget.js
> +    widgetLabels.mousedown(function () {
pode colocar nome pra ficar mais fácil de indetificar
```javascript
function onMouseDown() {
```

2018-12-17 23:03 UTC, icastro085 approved these changes

2018-12-18 19:29 UTC, marxguimaraes-bdev approved these changes

2018-12-18 19:30 UTC, marxguimaraes-bdev commented
LGTM

2018-12-18 19:33 UTC, merged