feat: add request and render products in carousel
chaordic/onsite-demo pull request #3
Opened 2018-09-24 18:35 UTC by cloped

Chamada para api de vitrines e renderização dos produtos recomendados em um carrossel.

2018-09-25 01:01 UTC, andrewcpacifico requested changes
Coloca um readme basicão ensinando a rodar o projeto, depois a gente evolui mais ele.

2018-09-25 01:01 UTC, andrewcpacifico commented on package.json
> +  "name": "onsite-demo",
@linx-impulse/onsite-demo

2018-09-25 01:01 UTC, andrewcpacifico commented on package.json
> +  "license": "ISC",
license: MIT

2018-09-25 01:01 UTC, andrewcpacifico commented on package.json
> +  "author": "",
remove o `author`, e coloca um array de `contributors`, e coloca teus  dados lá, igual tem no banner-client-js

2018-09-25 01:01 UTC, andrewcpacifico commented on src/index.js
> +};
Cria um form básico no topo da página pra passar essas informações. Dessa forma o teste fica dinâmico.

2018-09-25 01:01 UTC, andrewcpacifico commented on src/index.js
> +};
Pq ter essa função `request`, e não chamar o `getRecommendations` direto no `init`?

2018-09-25 13:40 UTC, cloped commented on src/index.js
> +};
Tentei deixar o mais resumido possível igual ao init do banner-js, e depois eu ainda colocaria o tracking de clicks no init, pensei que ficaria meio bagunçado.

2018-09-25 14:57 UTC, icastro085 requested changes

2018-09-25 14:57 UTC, icastro085 commented on .babelrc
> +        "@babel/preset-env"
2 espaços

2018-09-25 14:57 UTC, icastro085 commented on index.html
> +          <h2><b>top</b></h2>
espaçamento com 2 espaços

2018-09-25 14:57 UTC, icastro085 commented on index.html
> +          <h2><b>middle</b></h2>
espaçamento com 2 espaços

2018-09-25 14:57 UTC, icastro085 commented on index.html
> +          <h2><b>bottom</b></h2>
espaçamento com 2 espaços

2018-09-25 14:57 UTC, icastro085 commented on index.html
> +          <h2><b>novacolecao</b></h2>
espaçamento com 2 espaços

2018-09-25 14:57 UTC, icastro085 commented on package.json
> +    "babel-preset-env": "^1.7.0",
me parece que não está sendo usado, verifica se pode remover
https://babeljs.io/docs/en/env
https://babeljs.io/docs/en/babel-preset-env

2018-09-25 14:57 UTC, icastro085 commented on src/manager.js
> +import 'babel-polyfill';
já foi importado no index.js

2018-09-25 14:57 UTC, icastro085 commented on src/manager.js
> +                            </div>`);
acho que ficaria melhor assim, tah ocupando muitas colunas

```javascript
$(`#${divId}`).append(
  `<div id="${product.id}" class="row justify-content-center">
    <img src="${product.images.default}" class="rounded mx-auto d-block">
    <div class="m-1">${product.name}</div>
    <div class="m-1"><b>${product.price}</b></div>
  </div>
`);
```

2018-09-25 14:57 UTC, icastro085 commented on src/manager.js
> +                            </div>`);
eu acho que ficaria melhor assim
```javascript
$(`.${divClass}`).append(`
  <div>
    <p><h4> <b>Titulo vitrine: </b>${widget.title}</h4></p> 
    <div class="carousel" id="${divId}">
`);

insertProduct(widget,divId);

$(`.${divClass}`).append(`
    </div>
  </div>
`);
```

2018-09-25 14:57 UTC, icastro085 commented on src/manager.js
> +
remover essa linha

2018-09-25 14:57 UTC, icastro085 commented on style.css
> +    color: #8bc9e9;
espaçamento de 2 espaço

2018-09-25 14:57 UTC, icastro085 commented on style.css
> +color: #8bc9e9;
espaçamento de 2 espaço

2018-09-25 14:57 UTC, icastro085 commented on style.css
> +    height: 400px;
espaçamento de 2 espaço

2018-09-25 14:57 UTC, icastro085 commented on style.css
> +    margin: 0 10px;
espaçamento de 2 espaço

2018-09-25 14:57 UTC, icastro085 commented on style.css
> +    padding: 5px;
espaçamento de 2 espaço

2018-09-25 14:57 UTC, icastro085 commented on style.css
> +    margin: 0 -10px
espaçamento de 2 espaço

2018-09-25 14:57 UTC, icastro085 commented on src/manager.js
> +}
todo arquivo termina com uma nova lina(enter)

2018-09-25 14:57 UTC, icastro085 commented on style.css
> +}
todo arquivo termina com uma noa linha(enter)

2018-09-25 14:57 UTC, icastro085 commented on webpack.config.js
> +const path = require('path')
faltou ";"

2018-09-25 14:57 UTC, icastro085 commented on webpack.config.js
> +    filename: 'bundle.js'
faltou ","

2018-09-25 14:57 UTC, icastro085 commented on webpack.config.js
> +        use: 'babel-loader'
faltou ","

2018-09-25 14:57 UTC, icastro085 commented on webpack.config.js
> +      }
faltou ","

2018-09-25 14:57 UTC, icastro085 commented on webpack.config.js
> +    ]
faltou ","

2018-09-25 14:57 UTC, icastro085 commented on webpack.config.js
> +  }
faltou ","

2018-09-25 14:57 UTC, icastro085 commented on webpack.config.js
> +}
faltou ";" e "enter"

2018-09-25 14:57 UTC, icastro085 commented on src/manager.js
> +    if (!apiKey) {
espaçamento de 2 espaços

2018-09-25 14:57 UTC, icastro085 commented on src/manager.js
> +    }
espaçamento de 2 espaços

2018-09-25 14:57 UTC, icastro085 commented on src/manager.js
> +    if (!secretKey) {
espaçamento de 2 espaços

2018-09-25 14:57 UTC, icastro085 commented on src/manager.js
> +    }
espaçamento de 2 espaços

2018-09-25 14:57 UTC, icastro085 commented on src/manager.js
> +    if (!deviceId) {
espaçamento de 2 espaços

2018-09-25 14:57 UTC, icastro085 commented on src/manager.js
> +    }
espaçamento de 2 espaços

2018-09-25 14:57 UTC, icastro085 commented on src/manager.js
> +    if (!name) {
espaçamento de 2 espaços

2018-09-25 14:57 UTC, icastro085 commented on src/manager.js
> +    }
espaçamento de 2 espaços

2018-09-25 14:57 UTC, icastro085 commented on src/manager.js
> +    if (!source) {
espaçamento de 2 espaços

2018-09-25 14:57 UTC, icastro085 commented on src/manager.js
> +    }
espaçamento de 2 espaços

2018-09-25 14:57 UTC, icastro085 commented on src/manager.js
> +    return new Promise((resolve, reject) => {
espaçamento de 2 espaços, aqui e para as linhas seguintes

2018-09-25 17:49 UTC, cloped commented on src/manager.js
> +import 'babel-polyfill';
esse arquivo usa um await, se eu tento dar build sem o polyfill aqui dá erro

2018-09-27 18:49 UTC, icastro085 requested changes

2018-09-27 18:49 UTC, icastro085 commented on webpack.config.js
> +  entry: './src/index.js',
```javascript
entry: ['babel-polyfill', './src/index.js'],
```

2018-09-27 18:49 UTC, icastro085 commented on webpack.config.js
> +
remover essa linha

2018-09-27 18:49 UTC, icastro085 commented on src/manager.js
> +    await parse(response);
não precisa desse await

2018-09-27 18:49 UTC, icastro085 commented on package.json
> +  "main": "index.js",
não estaria dentro do "src"?

2018-09-27 18:49 UTC, icastro085 commented on package.json
> +    "start": "webpack-dev-server --content-base ./ --port 9000 --hot --mode development",
esse content-base tah errado, deveria ser o teu "dist" melhor colocar essas informações para o devServer no config do webpack, o mesmo para as outras informações de porta, hot e mode

2018-09-27 18:49 UTC, icastro085 commented on package.json
> +    "build": "npm run lint && webpack --mode development"
o lint pode ser feito no build do webpack

2018-09-27 18:49 UTC, icastro085 commented on src/index.js
> +import 'babel-polyfill';
tirar daqui e colocar no config do webpack

2018-09-27 18:49 UTC, icastro085 commented on src/index.js
> +import './style.css';
bixxxo, usa sass

2018-09-27 18:49 UTC, icastro085 commented on src/index.js
> +      $('#container-body').css('visibility', 'hidden');
melhor usar class css que fazer isso, cria uma!

2018-09-27 18:49 UTC, icastro085 commented on src/index.js
> +          deviceId: $('#deviceId').val(),
dica:
```javascript
response = await PageClient.getRecommendations(
  ['apiKey', 'secretKey', 'name', 'source', 'deviceId'].reduce((ob, key) => {
    ob[key] = $(`#${key}`).val();
    return ob;
  }, {})
);
```

2018-09-27 18:49 UTC, icastro085 commented on src/manager.js
> +import 'babel-polyfill';
tira!

2018-09-27 22:13 UTC, icastro085 requested changes

2018-09-27 22:13 UTC, icastro085 commented on README.md
> +const testObj = () => {
remover isso daqui

2018-09-27 22:13 UTC, icastro085 commented on src/index.js
> +import './style.css';
bixxxooo, sass

2018-09-27 22:13 UTC, icastro085 commented on src/index.js
> +            const ob = obj;
precisa disso?

2018-09-27 22:13 UTC, icastro085 commented on src/manager.js
> +  $(`.${divClass}`).append(`
já fez append antes, não precisa fechar, pode remover

2018-09-27 22:13 UTC, icastro085 commented on src/manager.js
> +      <div class="carousel" id="${divId}">
fecha essa div e colocar no final da string um "</div>"

2018-09-27 22:13 UTC, icastro085 commented on webpack.config.js
> +    inline: true,
seria bom definir também o host e port aqui, pois quando subir em uma imagem já vai está configurado
host: 0.0.0.0 => tem que ser esse ip, pois dá treta quando tu não faz isso dentro do container
port: 9000 => a porta que tu usa

2018-09-28 14:11 UTC, cloped commented on src/index.js
> +            const ob = obj;
sim por causa do lint, não pode mudar os parêmtros

2018-10-01 22:09 UTC, icastro085 requested changes

2018-10-01 22:09 UTC, icastro085 commented on src/index.js
> +            const ob = obj;
lembro de não poder mudar o valor da variável, mas de uma propriedade não era pra ocorrer

2018-10-01 22:09 UTC, icastro085 commented on src/index.js
> +    $('#try_btn').click(async () => {
muda essa callback do click pra uma função separada

2018-10-02 14:15 UTC, icastro085 requested changes
Já teve algumas coisas que comentei em outra PR, achei desnecessário falar aqui também. Então acredito que quando juntar tudo ficará melhor de ver.

2018-10-02 14:15 UTC, icastro085 commented on package.json
> +    "babel-polyfill": "^6.26.0",
devDependencies

2018-10-02 14:15 UTC, icastro085 commented on package.json
> +    "style-loader": "^0.23.0"
devDependencies

2018-10-02 14:15 UTC, icastro085 commented on src/index.js
> +  $('#try_btn').click(async () => {
mover esse callback para uma função separada

2018-10-02 14:15 UTC, icastro085 commented on src/index.js
> +  let response;
esse response não fez muito sentido, pode remover

2018-10-02 14:15 UTC, icastro085 commented on src/index.js
> +      response = {};
não precisa disso

2018-10-02 14:15 UTC, icastro085 commented on src/index.js
> +  return response;
pelo que vi, isso nunca vai acontecer

2018-10-02 14:15 UTC, icastro085 commented on src/index.js
> +function requestApi() {
esse nome, não diz oque essa função faz. pois ela apenas aplica um evento e não faz algo que possa retornar, poderia mudar para algo como "applyEventRequestApi" ou algo que você ache que fique melhor para a função.

2018-10-02 14:15 UTC, icastro085 commented on src/manager.js
> +  const filteredCategories = (categories || []).filter(category => category && category.id);
colocar a responsabilidade desse "filter" para uma outra função

2018-10-02 14:15 UTC, icastro085 commented on src/manager.js
> +  let item = filteredCategories.find(category => (
colocar a responsabilidade dessa "find" para uma outra função

2018-10-02 14:15 UTC, icastro085 commented on src/manager.js
> +    showLayout,
daqui pra frente, nenhum desse valores são passados pelo processo que você implementou, faz sentido ter eles? pois se fosse algo que mudasse em algum momento faria sentido, mas não vi mudando e se não precisa você passar um valor, então seria bom ter algo padrão de valor ou remover isso que não é usado por você

2018-10-02 18:10 UTC, cloped commented on src/manager.js
> +    showLayout,
Esse valores vão ser usados pra demo completa com outras vitrines

2018-10-03 21:59 UTC, icastro085 requested changes

2018-10-03 21:59 UTC, icastro085 commented on src/index.js
> +  $('#container-body').addClass('hided');
mover essa string para uma constante

2018-10-03 21:59 UTC, icastro085 commented on src/index.js
> +  $('#try_btn').click(applyEventRequestApi());
mover essa string para uma constante

2018-10-03 21:59 UTC, icastro085 commented on src/manager.js
> +    showLayout,
o showLayout não me parece ser do onsite server

2018-10-03 21:59 UTC, icastro085 commented on src/manager.js
> +    $('#json-file').empty();
colocar essa string numa constante

2018-10-03 21:59 UTC, icastro085 commented on src/manager.js
> +    $('#json-file').append(`
colocar essa string numa constante

2018-10-04 23:13 UTC, andrewcpacifico requested changes
Cara, eu vi muito código repetido em arquivos diferentes.

Outra coisa, acho que o código não tá muito fácil de entender. Lembra que esse código tem que ser uma espécie de documentação.

2018-10-04 23:13 UTC, andrewcpacifico commented on src/config/config.js
> +};
Tem um outro arquivo igualzinho em `src/config.js`

2018-10-04 23:13 UTC, andrewcpacifico commented on src/index.html
> +<html>
Esse arquivo é necessário? Tu não tirou ele e transformou em `ejs` ?

2018-10-05 18:17 UTC, icastro085 requested changes

2018-10-05 18:17 UTC, icastro085 commented on app/layout/containers/entry.ejs
> +         ApiKey<a class="text-danger">*</a>
acho que a tag mais adequada para essa informação do "*" seria usar não a tag "a" e sim a "span".
Obs: fazer isso para os demais lugar onde isso ocorre

2018-10-05 18:17 UTC, icastro085 commented on app/layout/containers/entry.ejs
> +      <label for="apiKey" class="control-label col-md-4 font-weight-bold">
erro de endentação, ajustar aqui e para os demais lugar onde isso ocorre.

2018-10-05 18:17 UTC, icastro085 commented on app/layout/containers/entry.ejs
> +      <div class="controls col-lg-12 ">
a estrutura desse teu forma está errada, faz um refactory usando como modelo o link:
https://getbootstrap.com/docs/4.0/components/forms/

2018-10-05 18:17 UTC, icastro085 commented on app/layout/containers/entry.ejs
> +      <label for="apiKey" class="control-label col-md-4 font-weight-bold">
esse col na label não faz sentido, remover isso e onde mais isso aparece

2018-10-05 18:17 UTC, icastro085 commented on app/layout/containers/entry.ejs
> +  <div class="jumbotron mb-5 p-">
o que faz esse "p-"? se não serve remove

2018-10-05 18:17 UTC, icastro085 commented on app/layout/containers/entry.ejs
> +    <form class="form-horizontal" method="post">
remover esse method, pois não vai ser usado o submit padrão do form

2018-10-05 18:17 UTC, icastro085 commented on app/layout/containers/entry.ejs
> +      <div class="col-md-auto">
não faz sentindo essa div aqui junto com esse col-md-auto

2018-10-05 18:17 UTC, icastro085 commented on app/layout/containers/json.ejs
> +<div class="row p-1">
eu acho que não faz sentido essa div, melhor remover

2018-10-05 18:17 UTC, icastro085 commented on app/layout/containers/widgets.ejs
> +  <b>Divs de vitrines:</b>
remover a tab b e ver se fica bold se não usa a classe correta para isso

2018-10-05 18:17 UTC, icastro085 commented on app/layout/containers/widgets.ejs
> +  <div class="top mt-2 border pl-5 pr-5 pt-3 pb-5 rounded"></div>
trocar todas as classes de padding e usar "px-5 e py-5" e onde mais isso ocorre

2018-10-05 18:17 UTC, icastro085 commented on app/layout/templates/widget.ejs
> +      <b>Tipo de vitrine: </b> <%= widget.feature %>
remover a tag b e usar a classe de bold se necessário

2018-10-05 18:17 UTC, icastro085 commented on app/layout/templates/widget.ejs
> +      <%- ejsInclude('product', { widget }); %>
o nome dessa função não ficou muito sugestivo, melhor trocar o nome para algo que diga que foi implementado de forma customizada

2018-10-05 18:17 UTC, icastro085 commented on app/styles/style.scss
> +pre {
esse "pre" não é genérico, deveria ser somente para quando tivesse a classe json-file como parent, mudar para dentro da mesma

2018-10-05 18:17 UTC, icastro085 commented on package.json
> +    "build:watch": "webpack -w --mode development",
mover esse mode para dentro das configurações do webpack, fazer isso onde mais está dessa forma

2018-10-05 18:17 UTC, icastro085 commented on src/managers/events.js
> +      deleteCookie('trackingUrl');
não precisa fazer isso se logo abaixo já vai ser sobrescrito

2018-10-05 18:17 UTC, icastro085 commented on src/managers/events.js
> +        ajax({
não precisa fazer isso em muitas linhas
```javascript
ajax({ url })
```

2018-10-05 18:17 UTC, icastro085 commented on src/managers/events.js
> +      arr.forEach((urlClick) => {
trocar urlClick para url e remover os parenteses e chaves e colocar a função do ajax na mesma linha

2018-10-05 18:17 UTC, icastro085 commented on src/index.js
> +import config from './config/config';
que porra é essa?

2018-10-05 18:17 UTC, icastro085 commented on src/managers/recommendations.js
> +import config from '../config/config';
rever isso

2018-10-05 18:17 UTC, icastro085 commented on src/managers/widget.js
> +    setTimeout(slickRender, 0);
bixxxooo, não era pra deixar esse setTimeout

2018-10-11 13:00 UTC, andrewcpacifico requested changes

2018-10-11 13:00 UTC, andrewcpacifico commented on src/components/widget.js
> +import ejs from 'ejs/ejs';
Esse `widget.js` ficou meio incoerente. No que diz respeito ao `render` ele é específico, renderiza uma única vitrine baseado nos dados que ele recebe de parâmetro. No que diz respeito aos eventos, ele analisa o contexto global, busca todas as vitrines, e registra o evento de todas.

Acho que seria melhor esse cara enxergar só o contexto específico. Pensa nele como um componente auto-suficiente. poderia ser uma classe com métodos `render` e `listenEvents`. E o método que varre os slots mandando renderizar iria instanciar um desses pra cada vitrine.

Ex:

```javascript
// index.js
renderWidget(data, div) {
  // futuramente aqui teria o código que identifica qual tipo de widget instanciar
  const widget = new Widget({ data, div });
  widget.render();
}

renderSlot(slotData) {
  slotData.forEach((widgetData) => {
    const widgetDiv = document.createElement('div');
    renderWidget(widgetData, widgetDiv);
  });
}
...

// widget.js
class Widget {
  constructor({ data, div }) {
    this.data = data;
    this.div = div;
    ...
  }
  ...
  render() {
    const rendered = ejs.render(template, data);
    this.div.innerHTML = rendered;
    // aplica as paradas do slick que não sei direito como é
    this.listenEvents();
  }

  listEvents() {
    // faz o registro dos eventos especificamente para essa vitrine
  }
  ...
}
```

2018-10-25 14:56 UTC, icastro085 requested changes

2018-10-25 14:56 UTC, icastro085 commented on src/components/widget.js
> +      window.open(product.url, '_blank');
melhor deixar esse redirect na tag "a" no próprio template

2018-10-25 14:56 UTC, icastro085 commented on src/index.js
> +  Object.keys(response).forEach((field) => { renderSlot(response[field], field); });
nessa caso pode ser feito assim:
```javascript
Object.keys(response).forEach(field => renderSlot(response[field], field));
```

2018-10-25 14:56 UTC, icastro085 commented on src/index.js
> +  setTimeout(slickRender, 0);
verificar qual o motivo de precisar desse setTimeout

2018-10-25 14:56 UTC, icastro085 commented on src/styles/style.scss
> +  color: purple;
sugiro que para toda cor usar um hex

2018-10-25 14:56 UTC, icastro085 commented on src/styles/style.scss
> +  box-shadow: 0px 0px 55px -10px rgba(0,0,0,0.14);
dá um espaço para cada virgula

2018-10-25 18:26 UTC, cloped commented on src/components/widget.js
> +      window.open(product.url, '_blank');
Segundo o @andrewcpacifico  o fluxo padrão de validação de clicks é por cookie.

2018-10-25 18:36 UTC, cloped commented on src/index.js
> +  Object.keys(response).forEach((field) => { renderSlot(response[field], field); });
ESLint não permite arrow function sem parênteses nos parâmetros.

2018-10-25 21:47 UTC, limafm commented on src/index.js
> +  Object.keys(response).forEach((field) => { renderSlot(response[field], field); });
Na real, deveria permitir se você retornar diretamente a função.
Assim como no exemplo do Ivanildo.

2018-10-29 15:57 UTC, icastro085 requested changes

2018-10-29 15:57 UTC, icastro085 commented on src/components/widget.js
> +      window.open(product.url, '_blank');
to falando do redirect não o evento de click

2018-10-29 15:57 UTC, icastro085 commented on src/styles/style.scss
> +  color: #800080;
colocar numa variável, está duplicando

2018-10-29 20:50 UTC, icastro085 requested changes

2018-10-29 20:50 UTC, icastro085 commented on layout/index.html
> +        <h1 class="text-center mb-3 font-weight-bold pl-0">Try onsite-demo</h1>
remove a porra toda "pl-0"

2018-10-29 20:50 UTC, icastro085 commented on layout/index.html
> +              <label for="apiKey" class="text-left font-weight-bold pl-0">
por padrão o texto sempre vem alinha à esquerda, não precisa dessa classe text-left. remove aqui e onde tiver

2018-10-29 20:50 UTC, icastro085 commented on layout/index.html
> +              <input class="input-md textinput form-control" id="apiKey" type="text" />
não vi nem definição dessa classe "textinput" e "input-md" remove a porra toda

2018-10-29 20:50 UTC, icastro085 commented on layout/index.html
> +              <label for="deviceId" class="text-left  font-weight-bold pl-0">
remover os dois espaços depois do "text-left" e junto ele

2018-10-29 20:50 UTC, icastro085 commented on package.json
> +    "build:watch": "webpack -w --mode development",
remove o mode

2018-10-29 20:50 UTC, icastro085 commented on package.json
> +    "build": "webpack --mode development"
remove o mode

2018-10-29 20:50 UTC, icastro085 commented on src/components/widget.js
> +    if (clickType.which !== 3) {
sei não hem!

2018-11-12 22:32 UTC, icastro085 approved these changes

2018-11-12 22:33 UTC, merged