feat: add widgets with one reference product
chaordic/onsite-demo pull request #6
Opened 2018-10-10 21:11 UTC by cloped

Adicionando suporte às seguintes vitrines: (ViewPersonzalized, PurchasePersonalized, CartPersonalized, UltimateBuy, Wishlist).

**Para testar**

- npm i
- npm run build
- npm run start
- Acessar a url localhost:9000
- Primeiramente ligar o plugin de CORS.
- Depois adicionar a seguinte função no arquivo index.js e chamá-la no init() com um await antes de renderizar.

```
const testObj = () => {
  $(() => {
    $('#apiKey').val('centauro-v5');
    $('#secretKey').val('LXthFHg1KQcyN1YTgUY3zg==');
    $('#name').val('home');
    $('#source').val('desktop');
    $('#deviceId').val('5abc10e0-c03e-11e8-8c80-eb2cc5f959c8');
  });
};
```

2018-10-25 15:05 UTC, icastro085 requested changes

2018-10-25 15:05 UTC, icastro085 commented on layout/templates/referenceWidget.ejs
> +      <button id="<%= widget.id %>-btn" class="btn rounded btn-primary p-1 pl-2 pr-2 float-right">
indentação

2018-10-25 15:05 UTC, icastro085 commented on layout/templates/referenceWidget.ejs
> +      <div class ="mt-2 ml-2"><%=  reference.name %></div>
espaço depois do "<%="

2018-10-25 15:05 UTC, icastro085 commented on layout/templates/referenceWidget.ejs
> +            <img src="https://<%= product.images.default %>" class="rounded mx-auto d-block img-fluid">
cuidado com esse "https" não deveria ser algo fixo

2018-10-25 15:05 UTC, icastro085 commented on layout/templates/widget.ejs
> +            <img src="https://<%= product.images.default %>" class="rounded mx-auto d-block img-fluid">
cuidado com esse "https" não era pra ser necessário

2018-10-25 15:05 UTC, icastro085 commented on src/components/referenceWidget.js
> +      window.open(product.url, '_blank');
deixar esse redirect na tag "a"

2018-10-25 15:05 UTC, icastro085 commented on src/components/referenceWidget.js
> +  && global.impressionReference.indexOf(reference.id) === -1) {
indetação

2018-10-25 15:05 UTC, icastro085 commented on src/components/referenceWidget.js
> +  });
pode deixar assim:
$(window).scoll(() => isViewed(widget));

2018-10-25 15:05 UTC, icastro085 commented on src/components/referenceWidget.js
> +    });
pode deixar assim:
```javascript
Object.keys(recs).forEach(indexRec => istenClicks(recs[indexRec]));
```

2018-10-25 15:05 UTC, icastro085 commented on src/components/referenceWidget.js
> +    const reference = widget.displays[0].references[0];
há a possibilidade de não ter esse displays?

2018-10-25 15:05 UTC, icastro085 commented on src/styles/style.scss
> +  color: #682c69;
está duplicando esse valor, coloca numa variável

2018-10-25 15:05 UTC, icastro085 commented on src/styles/style.scss
>    box-shadow: 0px 0px 55px -10px rgba(0,0,0,0.14);
colocar espaço depois de cada virgula

2018-10-25 15:05 UTC, icastro085 commented on src/utils.js
> +    centerPadding: '0px',
trocar '0px' para 0

2018-10-25 19:07 UTC, cloped commented on src/components/referenceWidget.js
> +    const reference = widget.displays[0].references[0];
Não que eu saiba, se a resposta da api vem, necessariamente vem com displays.

2018-10-29 16:04 UTC, icastro085 requested changes

2018-10-29 16:04 UTC, icastro085 commented on layout/index.html
> +        <div class="border rounded p-3 mt-3 mb-3">
trocar "mt-3 mb-3" por "my-3" e em todos os locais

2018-10-29 16:04 UTC, icastro085 commented on layout/index.html
> +      <hr class="my-3 mt-3">
tem o my-3 não precisa do mt-3

2018-10-29 16:04 UTC, icastro085 commented on layout/templates/referenceWidget.ejs
> +        <button id="<%= widget.id %>-btn" class="btn rounded btn-primary p-1 pl-2 pr-2 float-right">
"pl- pr-2" trocar para "px-2" e tirar esse p-1 colocar "py-1"

2018-10-29 16:04 UTC, icastro085 commented on src/components/referenceWidget.js
> +      window.open(product.url, '_blank');
faltou

2018-10-29 16:04 UTC, icastro085 commented on src/components/referenceWidget.js
> +    });
faltou aqui

2018-10-29 16:04 UTC, icastro085 commented on src/components/referenceWidget.js
> +    const reference = widget.displays[0].references[0];
blz

2018-10-29 16:04 UTC, icastro085 commented on src/components/widget.js
>        window.open(product.url, '_blank');
colocar isso na tag "a"

2018-10-29 16:04 UTC, icastro085 commented on src/components/widget.js
> +  $(window).scroll(() => { isViewed(widget); });
pode ser:
```javascript
 $(window).scroll(() => isViewed(widget));
```

2018-10-29 16:04 UTC, icastro085 commented on src/index.js
> +  const referenceWidgets = ['ViewPersonalized', 'PurchasePersonalized', 'CartPersonalized', 'UltimateBuy', 'Wishlist'];
quebra isso em mais linhas
```javascript
const referenceWidgets = [
  'ViewPersonalized',
  'PurchasePersonalized',
  'CartPersonalized',
  'UltimateBuy',
  'Wishlist',
];
```

2018-10-29 16:04 UTC, icastro085 commented on src/index.js
> +  $('#try_btn').click(() => { applyEventRequestApi(slickRender); });
remover as chaves ("{")

2018-11-22 21:48 UTC, marxguimaraes-bdev requested changes

2018-11-22 21:48 UTC, CrashToDesktop commented on src/styles/style.scss
> +// Adjusting arrows to sides.
Se essas duas classes fazem exatamente a mesma coisa não faz sentido ser uma só?

2018-11-23 00:26 UTC, cloped commented on src/styles/style.scss
> +// Adjusting arrows to sides.
eles mudam em um detalhe, left e right,

vou reduzir o q for em comum pra um seletor duplo

2018-11-26 13:03 UTC, marxguimaraes-bdev approved these changes

2018-11-26 13:04 UTC, CrashToDesktop commented
LGTM

2018-11-28 20:30 UTC, merged